name: Docker Push Jenkins Image

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t jungleismassive/jenkins:latest .

      - name: Push Docker image
        run: docker push jungleismassive/jenkins:latest